version: "3.9"

services:
  count_min_sketch_custom_implementation:
    container_name: count_min_sketch_custom_implementation
    image: python:3
    entrypoint: /project/entrypoint.sh
    command: python -u count-min-sketch-custom-implementation.py
    volumes:
      - ./src:/project
    environment:
      - RUN_TEST=${RUN_TEST:-0}
