version: "3.9"

services:
  hyper_log_log_custom_implementation:
    container_name: hyper_log_log_custom_implementation
    image: python:3
    entrypoint: /project/entrypoint.sh
    command: python -u hyper-log-log-custom-implementation.py
    volumes:
      - ./src:/project
    environment:
      - RUN_TEST=${RUN_TEST:-0}
