version: "3.9"

services:
  redis:
    container_name: count_min_sketch_size_redis
    image: redislabs/rebloom:latest
    deploy:
      restart_policy:
        condition: on-failure

      resources:
        limits:
          memory: ${DOCKER_REDIS_MEM_LIMIT:-2G}
    ports:
      - ${REDIS_PORT:-6379}:6379

  count_min_sketch_size:
    container_name: count_min_sketch_size
    image: python:3
    entrypoint: /project/entrypoint.sh
    command: python -u count-min-sketch-size.py
    depends_on:
      - redis
    volumes:
      - ./src:/project
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
